sudo: false
language: ruby
rvm:
  - 2.3.1
before_install:
  - gem uninstall bundler
  - gem install bundler -v 1.15.3
  - gem install rspec -v 3.5.0
script: rspec
env: VERBOSE=true
notifications:
    email: false
